name: AdvancedAllDart
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0
  archive: ^3.1.2
  pointycastle: ^3.1.3
  http: ^0.13.3

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
